### ISSUE TITLE
python 3.9 test failures

### ISSUE THREAD

**Issue by graingert** [testing-cabal/fixtures#44]
```
python -m testtools.run fixtures.test_suite

/opt/python/3.9-dev/lib/python3.9/runpy.py:127: RuntimeWarning: 'testtools.run' found in sys.modules after import of package 'testtools', but prior to execution of 'testtools.run'; this may result in unpredictable behaviour

  warn(RuntimeWarning(msg))

Tests running...

======================================================================

ERROR: fixtures.tests._fixtures.test_monkeypatch.TestMonkeyPatch.test_patch_classmethod_with_boundmethod

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/graingert/fixtures/fixtures/tests/_fixtures/test_monkeypatch.py", line 223, in test_patch_classmethod_with_boundmethod

    slf, cls = C.foo_cls()

TypeError: bar_two_args() missing 1 required positional argument: 'arg'

======================================================================

ERROR: fixtures.tests._fixtures.test_monkeypatch.TestMonkeyPatch.test_patch_classmethod_with_classmethod

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/graingert/fixtures/fixtures/tests/_fixtures/test_monkeypatch.py", line 191, in test_patch_classmethod_with_classmethod

    cls, target_class = C.foo_cls()

ValueError: not enough values to unpack (expected 2, got 1)


```

**Comment by thomasgoirand** [comment]
Hi.

Now that Python 3.9 reached Debian (and Ubuntu), Fixtures fails to build:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973239

It'd be nice if this could be solved. I have to admit I'm not sure what's going on...

**Comment by cjwatson** [comment]
I bisected this to this Python commit: https://github.com/python/cpython/commit/805f8f9afea116c5d4d000570e3d02ae84502f43

**Comment by cjwatson** [comment]
@alaski This seems to be an incompatibility between `classmethod` changes in Python 3.9 (see https://github.com/python/cpython/commit/805f8f9afea116c5d4d000570e3d02ae84502f43) and your `MonkeyPatch` changes in https://github.com/testing-cabal/fixtures/commit/78527ff5ab5452b5d91c361d040f3f31469b37ec.  Do you have any opinion on how it should best be fixed?

**Comment by fabaff** [comment]
Is there any progress here? Beside, Debian does this affect Fedora and NixOS as well.

**Comment by bnavigator** [comment]
#46

**Comment by cjwatson** [comment]
Looks like this should have been closed by merging #46.
